# Generated by Django 2.1.5 on 2019-01-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='type',
            field=models.CharField(blank=True, choices=[('sd', 'sedan'), ('sv', 'SUV'), ('vn', 'van'), ('lx', 'Luxury')], help_text='optional, vehicle type', max_length=2, null=True),
        ),
    ]
