# Generated by Django 2.1.5 on 2019-01-24 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190120_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='request',
        ),
        migrations.AddField(
            model_name='request',
            name='driver',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.Driver'),
        ),
    ]
