# Generated by Django 2.1.5 on 2019-01-24 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190123_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.Driver'),
        ),
    ]
