# Generated by Django 2.1.5 on 2019-01-25 00:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0005_auto_20190124_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular request', primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Date')),
                ('destination', models.CharField(max_length=200)),
                ('early_arrival_time', models.DateTimeField(blank=True, null=True)),
                ('late_arrival_time', models.DateTimeField(blank=True, null=True)),
                ('passenger_num', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('main_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.Request')),
                ('sharer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['create_date', 'sharer'],
            },
        ),
    ]
