# Generated by Django 2.1.5 on 2019-01-27 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_sharerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='total_passenger_num',
            field=models.IntegerField(null=True),
        ),
    ]
