# Generated by Django 2.1.5 on 2019-01-28 02:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_request_total_passenger_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='total_passenger_num',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
