# Generated by Django 2.1.5 on 2019-02-04 16:34

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_request_total_passenger_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='plate_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='arrival_time',
            field=models.DateTimeField(blank=True, null=True, validators=[orders.models.no_past]),
        ),
        migrations.AlterField(
            model_name='sharerequest',
            name='early_arrival_time',
            field=models.DateTimeField(blank=True, null=True, validators=[orders.models.no_past]),
        ),
    ]
