# Generated by Django 2.1.5 on 2019-02-06 00:14

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20190204_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharerequest',
            name='late_arrival_time',
            field=models.DateTimeField(blank=True, null=True, validators=[orders.models.no_past]),
        ),
    ]
