# Generated by Django 2.1.5 on 2019-02-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20190205_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='plate_number',
            field=models.CharField(max_length=20),
        ),
    ]
